server:
  port: 9000

spring:
  application:
    name: mssm-gateway-boot
  cloud:
    gateway:
      routes:
        - id: mssm-goods-router
          uri: lb://mssm-goods-boot
          predicates:
            - Path=/goods/**
        - id: mssm-photo-router
          uri: lb://mssm-photo-boot
          predicates:
            - Path=/photo/**
        - id: mssm-other-router
          uri: lb://mssm-other-boot
          predicates:
            - Path=/other/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true           #\u4F7F\u7528ip\u6CE8\u518C
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    lease-renewal-interval-in-seconds: 30     #\u79DF\u7EA6\u7EED\u7EA6\u95F4\u9694\u65F6\u95F4\uFF0C\u9ED8\u8BA430\u79D2
    lease-expiration-duration-in-seconds: 90  #\u79DF\u7EA6\u5230\u671F\uFF0C\u670D\u52A1\u6709\u6548\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u503C90\u79D2,\u670D\u52A1\u8D85\u8FC790\u79D2\u6CA1\u6709\u53D1\u751F\u5FC3\u8DF3\uFF0CEurekaServer\u4F1A\u5C06\u670D\u52A1\u4ECE\u5217\u8868\u79FB\u9664
  client:
    service-url:                        #eureka server \u5730\u5740
      defaultZone: http://113.31.144.141:9100/eureka
    register-with-eureka: true          #\u5411Eureka\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1\u7684\u4FE1\u606F (\u9ED8\u8BA4\u4E3Atrue)
    fetch-registry: true                #\u4ECEEureka Server\u83B7\u53D6\u670D\u52A1\u4FE1\u606F (\u9ED8\u8BA4\u4E3Atrue)
    registry-fetch-interval-seconds: 30 #\u6BCF\u9694\u591A\u4E45\u62C9\u53D6\u4E00\u6B21\u670D\u52A1\u5217\u8868